config:
  k8s-helidon-app:data:
    appName: k8s-helidon-app-otel
    namespace: dev
    deployment:
      replicas: 1
      image: "ghcr.io/shukawam/k8s-helidon-app-otel:latest"
      envs:
        - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
          value:
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value:
    ingress:
      host: helidon.otel.shukawam.me
      tls:
        hosts:
          - helidon.otel.shukawam.me
        secretName: shukawam-tls-secret
